export interface permission{
    "access.admin": boolean,
    "all.manage": boolean,
    "roles.manage": boolean,
    "users.view": boolean,
    "users.manage": boolean,
    "users.login_as": boolean,
    "clients.manage": boolean,
    "invoices.manage": boolean,
    "products.manage": boolean,
    "quotations.manage": boolean,
    "receipts.manage": boolean,
    "blogs.manage": boolean,
    "contact_us.manage": boolean,
    "settings.manage": boolean,
    "templates.manage": boolean,
    "orders.manage": boolean,
    "vouchers.manage": boolean,
    "plans.manage": boolean,
    "payment_links.manage": boolean,
    "reports.download": boolean,
    "reports.view": boolean,
    "revenues.view": boolean
}