export interface receipt{
    
        id: number,
        uuid: string,
        user_id: number,
        payment_transaction_id: string,
        invoice_id: string,
        invoice_number: number,
        bank_id: number,
        number: string,
        amount: number,
        received_at: string,
        payment_method: string,
        description: string,
        notes: string,
        customer_name: string,
        customer_address: string,
        customer_fax: string,
        customer_tax_number: string,
        created_at: string,
        month:string ,
        account_name: string,
        address: string,
        telephone: string,
        fax: string,
        tax_number: string,
        logo: string,
        signature: string
    
}